### ISSUE TITLE
[Patch] Patch to sync_first to not roll back if failed [sf#9]

### ISSUE THREAD

**Issue by bebehei** [rsnapshot/sourceforge-issues#8]
**Reported by phihoi on 2010-09-28 20:12 UTC**
When the sync_first option is used the rsnapshot behaviour is to rollback backups when the backup failed. I feel that the correct behaviour should be that the backup should not be rolled back on a failed synchronization, rather the rsync should continue where it was left off on the next iteration.

This patch increases the reliability of rsnapshot when used over bad links, the backup will eventually complete and rotate, when done. Without this patch failed backups creates a risk of failed backups and lost data if the failure happens over a longer period of time.

I use rsnapshot like this:

bash# rsnapshot sync && rsnapshot daily

I.e. Only rotate if the sync completes successfully. Rsnapshot will continue the next day if it failed.

--
Philippe

**Comment by bebehei** [comment]
**Commented by phihoi on 2010-09-28 20:12 UTC**
Patch to fix repeated sync
Attached filersnapshot.diff:

```
--- /usr/bin/rsnapshot  2010-08-24 20:58:07.000000000 +0200
+++ /tmp/rsnapshot.new  2010-08-28 00:44:18.000000000 +0200
@@ -3837,7 +3837,8 @@

        # set this directory to rollback if we're using link_dest
        # (since $interval.0/ will have been moved to $interval.1/ by now)
-       if (1 == $link_dest) {
+       # do not roll back when using sync_first, sync until successful, i.e. daily rotate should not be done if sync_first fails
+       if ((1 == $link_dest) && (! $config_vars{'sync_first'})) {
            push(@rollback_points, $$bp_ref{'dest'});
        }
    }
```

**Comment by sgpinkus** [comment]
I don't get this issue. In my testing if sync_first is enabled you need to pass the "sync" retain, to actually get any data transferred. On error rsync aborts and does not rollback. Other retain intervals simply rotate. This is regardless of the state of link_dest. I.e. when sync_first is enabled link_dest is N/A isn't it?

Maybe this is just the type of error condition I'm testing??:

```
...
/usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded \
    --rsh=/usr/bin/ssh \
    --link-dest=/tmp/rs-test/backups/hourly.1/localhost/ \
    sam@localhost:/tmp/rs-test/src/c \
    /tmp/rs-test/backups/.sync/localhost/ 
ssh: connect to host localhost port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(605) [Receiver=3.0.9]
----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot -vvvv -c rsnapshot.conf sync 
----------------------------------------------------------------------------
ERROR: /usr/bin/rsync returned 255 while processing sam@localhost:/tmp/rs-test/src/c
touch /tmp/rs-test/backups/.sync/ 
rm -f /tmp/rs-test/rsnapshot-test.lock 
```

**Comment by NicoK** [comment]
I don't have a minimal example now, but it is very annoying during backups if the first sync command (which I always execute before the 'weekly' command) rolls back all changes already transferred to an (external) HDD when e.g. a single file has vanished. Instead, it could leave the sync directory as it is and simply exit instead so I can continue where it left off:

[2015-12-16T00:10:03] /usr/bin/rsnapshot -vc rsnapshot.conf sync: started
[2015-12-16T00:10:03] Setting locale to POSIX "C"
[2015-12-16T00:10:03] echo 2254 > /var/run/media/backup-ext/rsnapshot/rsnapshot.pid
[2015-12-16T00:10:03] /usr/bin/rsync -aH --delete-after --no-inc-recursive --delete --numeric-ids --relative --delete-excluded --filter=merge <path to>/exclude.ext --link-dest=/var/run/media/backup-ext/rsnapshot/weekly.0/localhost/ /home/ /var/run/media/backup-ext/rsnapshot/.sync/localhost/
[2015-12-16T00:30:36] file has vanished: "<...>"
[2015-12-16T00:31:44] rsync warning: some files vanished before they could be transferred (code 24) at main.c(1165) [sender=3.1.0]
[2015-12-16T00:31:44] /usr/bin/rsnapshot -vc /home/nico/backup/rsnapshot.conf sync: ERROR: /usr/bin/rsync returned 0.09375 while processing /home
[2015-12-16T00:31:44] WARNING: /etc/ skipped due to rollback plan
[2015-12-16T00:31:45] WARNING: Rolling back "localhost/"
[2015-12-16T00:31:45] /bin/rm -rf /var/run/media/backup-ext/rsnapshot/.sync/localhost/
[2015-12-16T00:33:28] /bin/cp -al /var/run/media/backup-ext/rsnapshot/weekly.0/localhost /var/run/media/backup-ext/rsnapshot/.sync/localhost

**Comment by sgpinkus** [comment]
If you look [sub handle_rsync_error](https://github.com/rsnapshot/rsnapshot/blob/master/rsnapshot-program.pl#L4171), roll back only happens when the rsync return value is not 1, 23, 24. In the case above the return value is 24. The rollback is occurring because your using a broken version of rsnapshot.  Fixed in master.

I guess if a rollback should just _never_ occur when syncing then :+1: . But maybe there are cases where rsync/rsnapshot just doesn't know WTF is going on and wiping the slate clean is a feasible recovery strategy? Not sure.

**Comment by NicoK** [comment]
I'm using version 1.4.1 of rsnapshot (and v3.1.0 of rsync).

What is strange though is that rsnapshot states the following (after mentioning code 24): "/usr/bin/rsync returned 0.09375 while processing /home"
-> what is that supposed to mean?

**Comment by sgpinkus** [comment]
It's a bug, as I said, fixed in master.

**Comment by gkranis** [comment]
I will just leave this here cause it seems relevant:
Based on some quick checking of the source, haven't even tested it:
If link_dest and sync_first are both enabled and rsync encounters an error (not 1,23,24)  during "rsnapshot sync", rsnapshot will do a cp -al type of restore from lowest.0 to .sync. However unless I'm missing something this shouldn't be necessary since the initial state of .sync would be being non-existent, no? Unless someone plans to do rotate after sync which per the default usecase of rsnapshot sync && rsnapshot alpha wont happen anyway.
In the link_dest=false case rollback would have to happen because the .sync dir would be used as a source for the next sync interval and we wouldn't want to mess the space saving hardlinks...
